name: "Build CI Container Images"

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "Platform to build CCF against"
        required: true
        type: choice
        options: ["virtual", "sgx", "snp"]
  workflow_call:
    inputs:
      platform:
        description: "Platform to build CCF against"
        required: true
        type: string

env:
  ACR_REGISTRY: ccfmsrc.azurecr.io
  ACR_TOKEN_NAME: ci-push-token

jobs:
  build:
    name: "Build and Publish Pre-built SNP Container"
    runs-on: [self-hosted, 1ES.Pool=ccf-ci-github]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Docker
        run: |
          df -kh
          sudo echo '{"data-root": "/mnt"}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Log in
        run: docker login -u $ACR_TOKEN_NAME -p ${{ secrets.ACR_CI_PUSH_TOKEN_PASSWORD }} $ACR_REGISTRY

      - name: Pull CI container
        run: docker pull $ACR_REGISTRY/ccf/ci:02-02-2023-${{ inputs.platform }}

      - name: Build CCF CI SNP container
        run: docker build -f docker/ccf_ci_built . --build-arg="base=ccfmsrc.azurecr.io/ccf/ci:02-02-2023" --build-arg="platform=${{ inputs.platform }}" -t $ACR_REGISTRY/ccf/ci:${{ inputs.platform }}-`git rev-parse HEAD`

      - name: Push CI container
        run: docker push $ACR_REGISTRY/ccf/ci:${{ inputs.platform }}-`git rev-parse HEAD`
